# Generated by Django 5.1.2 on 2024-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donetion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donetion',
            name='doner_id',
        ),
        migrations.AddField(
            model_name='donetion',
            name='doner_name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
