# Generated by Django 5.1.2 on 2024-11-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_petdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petdetail',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_details', to='animal.pet'),
        ),
    ]
