# Generated by Django 5.1.2 on 2024-12-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_adopter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dosage', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
