# Generated by Django 5.1.2 on 2024-12-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_doctor_alter_medicine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopter',
            name='user',
        ),
    ]
